[package]
name = "snowcat"
version = "0.1.0"
authors = ["glotitude <ltoshchev@gmail.com>"]
edition = "2018"
readme = "README.md"

[dependencies]
snowcat_derive = { path = "snowcat_derive", version = "0.1.0" }

[workspace]
members = [
    "snowcat_derive",
]